"""
    ZeroTier Central API

    ZeroTier Central Network Management Portal API.<p>All API requests must have an API token header specified in the <code>Authorization: token xxxxx</code> format.  You can generate your API key by logging into <a href=\"https://my.zerotier.com\">ZeroTier Central</a> and creating a token on the Account page.</p><p>eg. <code>curl -X GET -H \"Authorization: token xxxxx\" https://api.zerotier.com/api/v1/network</code></p><p><h3>Rate Limiting</h3></p><p>The ZeroTier Central API implements rate limiting.  Paid users are limited to 100 requests per second.  Free users are limited to 20 requests per second.</p> <p> You can get the OpenAPI spec here as well: <code>https://docs.zerotier.com/openapi/centralv1.json</code></p>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.network_api import NetworkApi  # noqa: E501


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self):
        self.api = NetworkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_network(self):
        """Test case for delete_network

        delete network  # noqa: E501
        """
        pass

    def test_get_network_by_id(self):
        """Test case for get_network_by_id

        Get network by ID  # noqa: E501
        """
        pass

    def test_get_network_list(self):
        """Test case for get_network_list

        Returns a list of Networks you have access to.  # noqa: E501
        """
        pass

    def test_new_network(self):
        """Test case for new_network

        Create a new network.  # noqa: E501
        """
        pass

    def test_update_network(self):
        """Test case for update_network

        update network configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
