"""
    ZeroTier Central API

    ZeroTier Central Network Management Portal API.<p>All API requests must have an API token header specified in the <code>Authorization: token xxxxx</code> format.  You can generate your API key by logging into <a href=\"https://my.zerotier.com\">ZeroTier Central</a> and creating a token on the Account page.</p><p>eg. <code>curl -X GET -H \"Authorization: token xxxxx\" https://api.zerotier.com/api/v1/network</code></p><p><h3>Rate Limiting</h3></p><p>The ZeroTier Central API implements rate limiting.  Paid users are limited to 100 requests per second.  Free users are limited to 20 requests per second.</p> <p> You can get the OpenAPI spec here as well: <code>https://docs.zerotier.com/openapi/centralv1.json</code></p>  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.dns import DNS
from openapi_client.model.ip_range import IPRange
from openapi_client.model.ipv4_assign_mode import IPV4AssignMode
from openapi_client.model.ipv6_assign_mode import IPV6AssignMode
from openapi_client.model.route import Route
globals()['DNS'] = DNS
globals()['IPRange'] = IPRange
globals()['IPV4AssignMode'] = IPV4AssignMode
globals()['IPV6AssignMode'] = IPV6AssignMode
globals()['Route'] = Route
from openapi_client.model.network_config import NetworkConfig


class TestNetworkConfig(unittest.TestCase):
    """NetworkConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkConfig(self):
        """Test NetworkConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
